#!/bin/bash

SERVICE="sshd"
PID_FILE="/var/run/${SERVICE}.pid"
PID=$(sudo -E cat "${PID_FILE}" 2>/dev/null)

if [ "${PID}" == "" ]; then
  echo "${SERVICE} is not running"
  exit 0
fi

echo -n "Stopping ${SERVICE} [${PID}]..."
sudo -E kill "${PID}"
while [ -e "/proc/${PID}" ]; do
  echo -n "."
  sleep .5
done
sudo -E rm -f "${PID_FILE}"
echo "${SERVICE} stopped"
