#!/bin/bash 

echo "Stopping hadoop cluster..."
echo -en "     ... "
sudo -Eu "${HADOOP_USER}" "${SPARK_HOME}/sbin/stop-all.sh"
echo -e  "     ... stopping Hive"
for PID in $(sudo ps axf | grep "/hive" | grep -v grep | awk '{print $1}' | sort -n); do
    sudo kill -9 "${PID}"
done
echo -en "     ... stoping oozie"
sudo -Eu "${HADOOP_USER}" "${OOZIE_HOME}/bin/oozied.sh" stop
echo -en "     ... "
sudo -Eu "${HADOOP_USER}" "${HADOOP_HOME}/sbin/yarn-daemon.sh" stop nodemanager
echo -en "     ... "
sudo -Eu "${HADOOP_USER}" "${HADOOP_HOME}/sbin/yarn-daemon.sh" stop resourcemanager
echo -en "     ... "
sudo -Eu "${HADOOP_USER}" "${HADOOP_HOME}/sbin/hadoop-daemon.sh" stop datanode
echo -en "     ... "
sudo -Eu "${HADOOP_USER}" "${HADOOP_HOME}/sbin/hadoop-daemon.sh" stop secondarynamenode
echo -en "     ... "
sudo -Eu "${HADOOP_USER}" "${HADOOP_HOME}/sbin/hadoop-daemon.sh" stop namenode
echo "     ...done"

